# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75d42dc71000620aa248421ee15fa7cbf039570d712e66cc4f66815d23fd46fd92cb221a1b7e3fe2da390ef2a4bbbf6367064b387d79db7e364483ca8570348e

test:
  secret_key_base: 295e87c98f47d795288ae82c1285c0a3260c2779a470a4591795485fc0f5ea47af5fd9faf431373c8f72bc32672dcc5d51aa1769e5e3fa069a316b67faa8775a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
